server:
  port: 3344

spring:
  application:
    name: config-center

  cloud:
    config:
      server:
        git:
          uri: git@github.com:zzngb/springcloud-config.git
          #通过 localhost:3344/lable/config-dev.yml 即可访问
          search-paths: springcloud-config
      label: main

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

#rabbitmq 相关配置，暴露bus 刷新配置的端点。
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

