server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/yiyou?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Xxkjb6119!
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos 地址
management:
  endpoints:
    web:
      exposure:
        include: '*'
